const data = [
  {
    id: 1,
    title: 'sidebar',
    image: './images/image.jpg',
    link: 'https://sidebarexample.netlify.app',
  },
  {
    id: 2,
    title: 'about',
    image: './images/image (1).jpg',
    link: 'https://tabs-examples.netlify.app',
  },
  {
    id: 3,
    title: 'counter',
    image: './images/image (2).jpg',
    link: 'https://two-counter-example.netlify.app',
  },
  {
    id: 4,
    title: 'lorem ipsum',
    image: './images/image (3).jpg',
    link: 'https://lorem-ipsum-example.netlify.app',
  },
  {
    id: 5,
    title: 'navbar',
    image: './images/image (6).jpg',
    link: 'https://navbarexample.netlify.app',
  },
  {
    id: 6,
    title: 'simple counter',
    image: './images/image (7).jpg',
    link: 'https://counterexample.netlify.app',
  },
  {
    id: 7,
    title: 'filter',
    image: './images/image (9).jpg',
    link: 'https://filter-example.netlify.app',
  },
  {
    id: 8,
    title: 'grocery bud',
    image: './images/image (11).jpg',
    link: 'https://grocery-bud-example.netlify.app',
  },
  {
    id: 9,
    title: 'slider',
    image: './images/image (13).jpg',
    link: 'https://slider-example-two.netlify.app',
  },
  {
    id: 10,
    title: 'questions',
    image: './images/image (14).jpg',
    link: 'https://questionsexample.netlify.app',
  },
  {
    id: 11,
    title: 'scroll',
    image: './images/image (17).jpg',
    link: 'https://scroll-example.netlify.app',
  },
  {
    id: 12,
    title: 'reviews',
    image: './images/image (18).jpg',
    link: 'https://reviewsexample.netlify.app',
  },
  {
    id: 13,
    title: 'countdown timer',
    image: './images/image (19).jpg',
    link: 'https://countdown-timer-example.netlify.app',
  },
  {
    id: 14,
    title: 'menu',
    image: './images/image (20).jpg',
    link: 'https://menuexamples.netlify.app',
  },
  {
    id: 15,
    title: 'color flipper',
    image: './images/image (21).jpg',
    link: 'https://color-flipperexample.netlify.app',
  },
  {
    id: 16,
    title: 'modal',
    image: './images/image (23).jpg',
    link: 'https://modalexamples.netlify.app',
  },
  {
    id: 17,
    title: 'back tour',
    image: './images/image(28).png',
    link: 'https://road-trip-example.netlify.app',
  },
  {
    id: 18,
    title: 'tea station',
    image: './images/image(29).png',
    link: 'https://tea-station-example.netlify.app',
  },
  {
    id: 19,
    title: 'normal slider',
    image: './images/imzge (30).png',
    link: 'https://slider-example-one.netlify.app',
  },
  {
    id: 20,
    title: 'video',
    image: './images/image (5).jpg',
    link: 'https://videoexample.netlify.app',
  },
];
